version: '3'

networks:
  roadmap_links:


volumes:
  mysql:
    driver: local
  redis:
    driver: local

services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=roadmap_links
    restart: unless-stopped
    container_name: roadmap_links-nginx
    depends_on:
      - mysql
      - php
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www/html
    networks:
      - roadmap_links

  php:
    build:
      context: ./docker/php8.1-fpm
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=roadmap_links
    container_name: roadmap_links-php
    ports:
      - ':9000'
    volumes:
      - ./:/var/www/html
    networks:
      - roadmap_links

  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: roadmap_links-mysql
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - roadmap_links
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-p${DB_PASSWORD}' ]
      retries: 3
      timeout: 5s

  redis:
    image: redis:alpine
    container_name: roadmap_links-redis
    restart: unless-stopped
    ports:
      - 6381:6379
    volumes:
      - redis:/data
    networks:
      - roadmap_links

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: roadmap_links-phpmyadmin
    hostname: localhost
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_PORT: ${DB_PORT}
    depends_on:
      - mysql
    ports:
      - 8888:80
    networks:
      - roadmap_links

  composer:
    build:
      context: ./docker
      dockerfile: composer.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=roadmap_links
    container_name: roadmap_links-composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: roadmap_links #system user
    profiles: [ 'composer' ]
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
    networks:
      - roadmap_links

  artisan:
    build:
      context: ./docker/php8.1-fpm
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=roadmap_links
    container_name: roadmap_links-artisan
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
      - mysql
    working_dir: /var/www/html
    profiles: [ 'artisan' ]
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      - roadmap_links

  npm:
    image: node:alpine
    container_name: roadmap_links-npm
    volumes:
      - ./:/var/www/html
    ports:
      - 3000:3000
      - 3001:3001
      - 5173:5173
    working_dir: /var/www/html
    profiles: [ 'npm' ]
    entrypoint: [ 'npm' ]
    networks:
      - roadmap_links
